cbnu-sequence/sequence-web-front

.dockerignore
.gitignore
Dockerfile.dev
config/config.ts-help

Docker-compose로 묶기 위해 Dockerizing

Feat: 추가 Dockerfile.dev Dockerfile.dev config.ts-help & 수정 .gitignore

---

package-lock.json
package.json
pages/LogIn/test/Login.test.tsx
pages/SignUp/test/signup.test.tsx
yarn.lock

로그인, 회원가입 렌더링 테스트코드 추가했습니다. (#3)

로그인, 회원가입 렌더링 테스트코드

---

pages/LogIn/test/Login.test.tsx
pages/SignUp/test/signup.test.tsx
pages/emailcheck/test/emailcheck.test.tsx

test 수정 및 email UI test 추가했습니다

test 수정 및 email UI test 추가

---

apis/post.ts
components/Pagination/index.tsx
components/Pagination/styles.tsx
components/PostDetail/index.tsx
components/Table/styles.tsx
pages/board/notice.tsx
pages/posts/[id].tsx
react-query/constants.ts

게시글 디테일 페이지 

---

components/Header/index.tsx
components/Header/styles.tsx
components/writeboard/index.tsx
components/writeboard/styles.tsx
yarn.lock

Design: 화이트 헤더 추가, 글쓰기 페이지 디자인 수정

---

components/Header/styles.tsx

Add: 모바일뷰 헤더 서브메뉴 겹침 수정

---

components/Buttons/WriteBtn.tsx
pages/board/notice/index.tsx

user role에 따라 글쓰기 버튼 보이게 추가하였습니다. 
디자인적인 요소에 추가가 필요합니다.

Add: user role에 따라 글쓰기 버튼 보이기

---

apis/post.ts
components/Header/index.tsx
components/PostDetail/index.tsx
components/Table/CommonTable.tsx
components/Table/styles.tsx
pages/board/notice/index.tsx
pages/board/sharinginfo/index.tsx
pages/posts/[id].tsx
react-query/constants.ts
styles/globals.css
yarn.lock

정보공유 게시판 추가하였고 카테고리에 따른 param일반화하여 카테고리에 따른 게시판 구별을 해놓았습니다.

Fix: 정보공유 게시판 확인 및 큰 카테고리에 따른 param 일반화

---

components/Buttons/DeleteBtn.tsx
components/Buttons/ModifyBtn.tsx
components/Buttons/WriteBtn.tsx
components/Buttons/styles.tsx
pages/board/notice/index.tsx

#40 
Write, Delete, Modify 버튼 모양 + hover 만들었습니다.
Btns 3가 최종입니다.

#40 컴포넌트 글쓰기 버튼 - 수정

---

apis/post.ts
components/Header/index.tsx
components/Main/index.tsx
components/PostDetail/index.tsx
components/PostDetail/styles.tsx
components/PostHeader/index.tsx
components/PostHeader/styles.tsx
hooks/roleToKr.ts
pages/index.tsx
pages/posts/[id].tsx

#41
serversideProps로 내 정보 불러오는 걸 하였습니다.

[SSR] 홈화면 getServerSideProps를 이용하여 내 정보 불러오기

---

components/PostDetail/index.tsx
components/PostDetail/styles.tsx
components/PostFiles/index.tsx
components/PostHeader/index.tsx
components/PostHeader/styles.tsx
components/PostImages/index.tsx
pages/posts/[id].tsx
pages/profile/index.tsx

dev 브랜치로 올려서 테스트하겠습니다. 
리뷰해야할 거 있으면 부탁드려요

게시글 디테일 페이지 디자인 추가

---

components/writeboard/index.tsx

Add: 파일 url 전달 수정

---

components/Main/styles.tsx
yarn.lock

홈화면 (탑)글씨크기 수정

---

components/writeboard/index.tsx
components/writeboard/styles.tsx

Add: 파일 삭제 버튼 추가

---

components/Table/styles.tsx
pages/profile/index.tsx
pages/profile/styles.tsx

마이페이지 디자인 추가했습니다. (반응형 (게시판 공백) 수정 필요)

add: 마이페이지(프로필) 스타일

---

pages/404/index.tsx
pages/404/styles.tsx

Add: 404 페이지 추가

---

components/Header/index.tsx

Add: 헤더 useEffect 오류 수정

---

pages/members/index.tsx
yarn.lock

Add: 부원 소개 페이지 설명 추가

---

apis/post.ts
apis/user.ts
components/OAuth2RedirectHandler.tsx
components/WriteBoard/index.tsx
pages/board/notice/index.tsx
pages/board/sharinginfo/index.tsx
pages/board/write/index.tsx
pages/index.tsx
pages/login/index.tsx

카카오 로그인 에러 픽스

---

pages/index.tsx

data가 null 값일 수 있어 생긴 에러를 수정했습니다.

홈화면 서버사이드 렌더링 오류 수정

---

components/ProjectWrite/index.tsx
components/ProjectWrite/styles.tsx
components/WriteBoard/index.tsx
components/WriteBoard/styles.tsx
components/WriteBoard/texteditor.tsx
pages/introduce/index.tsx
styles/introduce.ts

response status처리 및 반응형 디자인 수정

---

hooks/useAuth.ts
pages/emailcheck/index.tsx
pages/login/index.tsx
pages/signup/index.tsx

회원가입쪽 라우팅 에러 및 에러처리 완료하여 올립니다~

Fix: 회원가입 쪽 라우팅 에러

---

components/Timer/index.tsx
components/Timer/styles.ts
components/TimerForm/styles.ts
pages/pomodoro/index.tsx
pages/pomodoro/ranking/index.tsx
styles/pomodoro.ts

타이머 디자인 추가하였습니다. 

---

apis/user.ts
components/Header/index.tsx
components/Header/styles.tsx
hooks/useProjectMembers.ts
pages/members/manager/index.tsx
pages/members/projectteam/index.tsx
pages/members/techcourseteam/index.tsx
styles/projectTeam.ts
styles/techcourseTeam.ts
yarn.lock

Add: 부원 소개 페이지 추가

---

apis/pomodoro.ts
components/MyPomo/index.tsx
components/MyPomo/styles.ts
components/PomoProgress/index.tsx
components/PomoProgress/styles.ts
components/Ranking/index.tsx
components/Timer/index.tsx
components/TimerForm/index.tsx
pages/pomodoro/index.tsx
react-query/constants.ts
styles/pomodoro.ts

Add: 나의 뽀모도로 리스트

---

components/Header/styles.tsx
components/Timer/styles.ts
components/TimerForm/index.tsx
components/TimerForm/styles.ts
styles/constants.js
styles/introduce.ts

introduce-lab파트 디자인 마무리 및 뽀모도로 1차 스타일 추가했습니다.

introduce-lab파트 디자인 마무리 및 뽀모도로 1차 스타일 추가

---

components/Buttons/styles.tsx
components/NoList/index.tsx
pages/board/projects/mobile/index.tsx
pages/board/sharinginfo/mobile/index.tsx

Add: ios앱 웹뷰용 화면 추가 

---

components/Main/index.tsx
components/Main/styles.tsx
components/PomoProgress/styles.ts
components/ProjectCard/styles.tsx
components/ProjectImage/styles.tsx
components/Slider/styles.tsx
components/Timer/index.tsx
components/Timer/styles.ts
components/TimerForm/styles.ts
pages/pomodoro/index.tsx
styles/pomodoro.ts

뽀모도로 디자인 2차 수정 (반응형 포함)

---

apis/user.ts
components/Header/styles.tsx
interfaces/user.ts
pages/emailcheckprofile/index.tsx
pages/members/manager/index.tsx
pages/profile/index.tsx
react-query/constants.ts
styles/profile.ts

Add: 프로필 수정 추가

---

components/Header/styles.tsx
components/Main/index.tsx
components/Main/styles.tsx
styles/introduce.ts

- 홈화면: margin문제 해결, 뽀모도로&시퀀스더보기 링크 수정
-  시퀀스 소개: lab파트 모바일 뷰 수정
-  헤더: 모바일 뷰 수정

메인 & 헤더 오류 수정

---

pages/emailcheckprofile/index.tsx
pages/profile/index.tsx

Add: 프로필 수정하기 기능 수정

---

apis/pomodoro.ts
components/PomoRanking/index.tsx
components/RankingTabContent/index.tsx
components/TimerForm/index.tsx
hooks/useRanking.ts
interfaces/pomodoro.ts
pages/pomodoro/index.tsx
react-query/constants.ts
styles/globals.css
styles/pomodoro.ts
styles/ranking.ts

랭킹 테이블 css를 제외한 나머지 기능을 완료하였습니다.

[뽀모도로] 랭킹 시스템 추가

---

components/ProjectCard/styles.tsx
components/Slider/index.tsx

Add: 홈 화면 프로젝트 슬라이더 부분 수정

---

pages/members/manager/index.tsx
styles/manager.ts

Add:운영진 페이지 추가

---

apis/user.ts
pages/board/sharinginfo/mobile/index.tsx
pages/board/sharinginfo/mobile/posts/[id].tsx
pages/login/index.tsx
pages/posts/[id].tsx
styles/pomodoro.ts

자꾸 내 정보가 빠지는 오류가 있어 수정하였습니다.
그리고 앱 모바일뷰 고려하여 수정해보았습니다.(테스트 필요)

Fix: 인증오류와 모바일 뷰

---

pages/pomodoro/index.tsx

타이머 설정을 바꾸며 끝내는 로직을 빼먹었습니다.
다시 추가하였습니다.

Fix: 뽀모도로 안 끝나는 에러 픽스

---

components/Timer/index.tsx
components/Timer/styles.ts

Fix: 뽀모도로 border 애니메이션 오류

---

hooks/useAuth.ts
pages/login/index.tsx
pages/signup/index.tsx
styles/signup.ts

Add: 회원가입 버튼 수정

---

apis/post.ts
components/ImageSlider/index.tsx
components/ImageSlider/styles.tsx
components/ProjectCard/index.tsx
components/ProjectCard/styles.tsx
components/ProjectDetail/index.tsx
components/ProjectDetail/styles.tsx
components/ZoomImage/index.tsx
components/ZoomImage/styles.tsx
package-lock.json
pages/project/[id].tsx
yarn.lock

Add: 프로젝트 디테일 페이지 추가

---

components/ImageSlider/index.tsx
components/ImageSlider/styles.tsx
components/ProjectDetail/index.tsx
components/ProjectDetail/styles.tsx
components/ZoomImage/index.tsx
components/ZoomImage/styles.tsx

Add: 프로필 페이지 디자인 수정

---

README.md

Add: Readme수정

---

components/Header/index.tsx
pages/signup/index.tsx
styles/signup.ts

회원가입&로그인 창 오류, 헤더 오류 수정

---

components/ProjectCard/styles.tsx
components/ProjectImage/styles.tsx
pages/board/projects/index.tsx
pages/board/sharinginfo/index.tsx
styles/projects.ts

모바일뷰에서 너비 하나당 한 프로젝트씩 나오게 수정하였습니다.

프로젝트 게시판 모바일 뷰 고쳤습니다.

---

apis/post.ts
components/EditBoard/index.tsx
components/PostDetail/index.tsx
components/PostDetail/styles.tsx
pages/posts/[id].tsx
pages/posts/edit/[id].tsx
user-storage/user-storage.ts

Add: 게시판 수정 기능 추가

---

components/ProjectDetail/styles.tsx
components/ZoomImage/styles.tsx

Add: 프로젝트 디테일 페이지 디자인 수정

---

styles/projectTeam.ts
styles/techcourseTeam.ts

부원 소개의 프로젝트팀, 테크코스팀 디자인 수정하였습니다.

부원소개 - 프로젝트팀, 테크코스팀 디자인 수정하였습니다.

---

components/EditBoard/index.tsx
pages/posts/edit/[id].tsx

Add: ssr작업 추가

---

pages/profile/index.tsx

Add: 프로필 페이지 기능 오류 수정

---

pages/board/notice/index.tsx
pages/index.tsx
pages/pomodoro/index.tsx
styles/PomoDoroBody.ts

공지사항과 뽀모도로 페이지를 ssr했습니다.
현재 뽀모도로 page는 style적인 요소도 props로 받고 있어 이도 함께 처리하였습니다.
일단 내 정보를 ssr하여 현재 실서버에 나는 에러를 방지하였습니다.

Add: 공지사항과 뽀모도로 ssr

---

apis/user.ts
pages/profile/index.tsx
styles/profile.ts

Add: 프로필 페이지 멤버 정보 변경 기능 추가

---

components/ManagerCard/styles.tsx
components/ProfileModal/styles.tsx
pages/members/manager/index.tsx
styles/manager.ts
styles/techcourseTeam.ts

부원 소개 - 운영진 소개 및 모바일 뷰 수정했습니다.

---

components/Header/index.tsx
components/Header/styles.tsx
components/ProjectCard/index.tsx
pages/_app.tsx
pages/profile/index.tsx

헤더 아이콘 에러가 날 수 있는 부분들을 체크하여 수정하였습니다.
dev브랜치에서 확인해볼 것입니다.

Fix: 헤더 아이콘 에러

---

cypress/integration/home.ts

Add: 홈화면 cypress 테스트 코드 추가

---

components/Slider/index.tsx

프로젝트 slick 모바일뷰 수정

---

components/HeadMeta/index.tsx
components/ImageSlider/styles.tsx
components/ProjectCard/index.tsx
components/ProjectDetail/index.tsx
pages/_document.tsx
pages/posts/[id].tsx
pages/project/[id].tsx
react-query/constants.ts

프로젝트 디테일쪽 서버사이드 렌더링 코드 작성하였습니다.
메타 태그 작성하여 document안에 넣는 식으로 해보았는데 dev로 합쳐 테스트 하려합니다.

프로젝트 디테일 서버사이드 렌더링과 메타 태그 추가하여 seo

---

components/Header/index.tsx
components/Header/styles.tsx

(#159) 헤더 css 리팩토링 작업을 통해 코드 130줄 정도를 줄였습니다.

Add: 헤더 리팩토링

---

components/EmailCheckProfile/index.tsx
components/EmailCheckProfile/styles.tsx
pages/profile/index.tsx
styles/profile.ts

프로필 디자인 수정

---

components/ImageSlider/index.tsx
components/ImageSlider/styles.tsx
components/ProjectDetail/index.tsx
components/ProjectDetail/styles.tsx
components/ZoomImage/index.tsx
components/ZoomImage/styles.tsx

> 최대한 Block, Element, Modifier를 정확히 나누려고 노력하였는데, 부족한 점 있으면 말해주시면 감사하겠습니다

Add: 프로젝트 디테일 페이지 수정

---

components/ProfileModal/styles.tsx
pages/members/manager/index.tsx
pages/members/techcourseteam/index.tsx
styles/techcourseTeam.ts

Support: 부원소개 모바일뷰 수정

---

components/ProfileModal/styles.tsx

Fix: 운영진 페이지 괄호 수정

---

apis/post.ts
components/HeadMeta/index.tsx
hooks/usePomodoro.ts
hooks/useProjects.ts
interfaces/headmeta.ts
interfaces/post.ts
interfaces/project.ts
pages/_document.tsx
pages/board/notice/index.tsx
pages/board/projects/index.tsx
pages/board/sharinginfo/index.tsx
pages/index.tsx
pages/project/[id].tsx

headmeta를 페이지 안에 넣는 식으로 해결하였습니다.

메타 태그가 안 먹는 오류가 있어 메타 태그를 프로젝트와 메인 페이지에 추가하였습니다.

---

apis/post.ts
components/HeadMeta/index.tsx
pages/project/[id].tsx

Fix: 메타태그의 오타 수정

---

components/HeadMeta/index.tsx

콘솔창에 오류가 생겨 html lang 부분을 제거하였더니 해결됐습니다.

Fix: next-head 오류해결 작업
